### ISSUE TITLE
Error in UMS 3.4.2

### ISSUE THREAD

**Issue by MauricioLucas** [chocolateboy/pmsencoder#7]
PMSEncoder: initializing PMSEncoder 2.0.0-rc3
  PMSEncoder: build: 40ce842 (2013-11-23)
  PMSEncoder: script directory: C:\Program Files (x86)\Universal Media Server\scripts
  PMSEncoder: log directory: C:\ProgramData\UMS
  PMSEncoder: loading built-in log4j config file: jar:file:/C:/Program%20Files%20(x86)/Universal%20Media%20Server/plugins/pmsencoder-2.0.0-rc3.jar!/log4j_default.xml
  Exception in thread "main" java.lang.VerifyError: (class: com/chocolatey/pmsencoder/PMSEncoder, method: super$4$getAudioBitrateOptions signature: (Lnet/pms/dlna/DLNAResource;Lnet/pms/dlna/DLNAMediaInfo;Lnet/pms/io/OutputParams;)Ljava/util/List;) Illegal use of nonvirtual function call
    at com.chocolatey.pmsencoder.Plugin.<init>(Plugin.groovy:185)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at java.lang.Class.newInstance(Unknown Source)
    at net.pms.external.ExternalFactory.instantiateEarlyListeners(ExternalFactory.java:419)
03-20 08:04:40      at net.pms.external.ExternalFactory.lookup(ExternalFactory.java:399)
    at net.pms.PMS.init(PMS.java:635)
    at net.pms.PMS.createInstance(PMS.java:1027)
    at net.pms.PMS.main(PMS.java:1125)
- I have instaled the last Java Runtime Environment, Version 7 Update 51

**Comment by chocolateboy** [comment]
[UMS is not supported](https://github.com/chocolateboy/pmsencoder#prerequisites).

**Comment by MauricioLucas** [comment]
Ok, not support, but many people use your plugin in Universal Media Server. Most plugins PS3 Media Server are supported in UMS, why not make your compatible work again as it was before? 
http://www.universalmediaserver.com/forum/viewtopic.php?f=6&t=1123

Look "Manual-install plugins", have many another plugins PS3MS also portable for UMS.
http://www.universalmediaserver.com/plugins/

*"Everyone loves your plugin, please extend your magic hand on us"
